name: Dependency Update Check

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual trigger

jobs:
  dependency-check:
    name: Check Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check for outdated packages
        run: |
          echo "## Outdated Dependencies" >> $GITHUB_STEP_SUMMARY
          npm outdated --long || echo "All dependencies are up to date!" >> $GITHUB_STEP_SUMMARY

      - name: Audit dependencies
        run: |
          echo "## Security Audit" >> $GITHUB_STEP_SUMMARY
          npm audit --audit-level=moderate || echo "Security vulnerabilities found!" >> $GITHUB_STEP_SUMMARY

      - name: Check bundle size
        run: |
          npm run build
          echo "## Bundle Analysis" >> $GITHUB_STEP_SUMMARY
          du -sh .next/ >> $GITHUB_STEP_SUMMARY
